"use client";

import * as React from "react";
import {
  Download,
  Images,
  Merge,
  AlertTriangle,
  CheckCircle,
} from "lucide-react";
import {
  Card,
  CardContent,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { getAllSubjectsByUserId } from "@/db/queries/subjects";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { handleDownload } from "@/utils/zip";
import Image from "next/image";

// Type definitions
interface SubjectWithCover {
  id: string;
  name: string;
  coverUrl: string | null;
  photoCount: number | null;
}

interface MergeSuggestion {
  id: string;
  person1: SubjectWithCover;
  person2: SubjectWithCover;
  confidence: number;
  reason: string;
}

const SubjectsGrid = () => {
  const [searchTerm, setSearchTerm] = React.useState("");
  const [selectedTab, setSelectedTab] = React.useState("all");
  const [showMergeDialog, setShowMergeDialog] = React.useState(false);
  const [mergeSuggestions, setMergeSuggestions] = React.useState<
    MergeSuggestion[]
  >([]);

  const {
    data: subjects,
    isPending,
    isError,
  } = useQuery({
    queryKey: ["subjects"],
    queryFn: async () => getAllSubjectsByUserId(),
  });

  // Mock merge suggestions - replace with actual API call
  React.useEffect(() => {
    if (subjects) {
      // Simulate merge suggestions for auto-generated names
      const suggestions = subjects
        .filter(
          (subject) =>
            subject.name.startsWith("Person_") ||
            subject.name.startsWith("Unknown_"),
        )
        .slice(0, 2)
        .map((subject, index) => ({
          id: `suggestion_${index}`,
          person1: subject,
          person2:
            subjects.find(
              (s) =>
                s.id !== subject.id &&
                (s.name.startsWith("Person_") || s.name.startsWith("Unknown_")),
            ) || subject,
          confidence: 0.85,
          reason: "High facial similarity detected",
        }));
      setMergeSuggestions(suggestions);
    }
  }, [subjects]);

  if (isPending) {
    return (
      <div className="min-h-screen bg-photo-stone-50 p-6">
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="text-center space-y-4">
            <div className="w-12 h-12 border-4 border-photo-green-300 border-t-transparent rounded-full animate-spin mx-auto"></div>
            <p className="text-photo-stone-600">Loading people...</p>
          </div>
        </div>
      </div>
    );
  }

  if (isError) {
    return (
      <div className="min-h-screen bg-photo-stone-50 p-6">
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="text-center space-y-4">
            <div className="w-12 h-12 bg-photo-rose-100 rounded-full flex items-center justify-center mx-auto">
              <AlertTriangle className="w-6 h-6 text-photo-rose-500" />
            </div>
            <p className="text-photo-stone-600">
              Error loading people. Please try again.
            </p>
          </div>
        </div>
      </div>
    );
  }

  const filteredSubjects = subjects.filter((subject) =>
    subject.name.toLowerCase().includes(searchTerm.toLowerCase()),
  );

  const autoGeneratedSubjects = subjects.filter(
    (subject) =>
      subject.name.startsWith("Person_") || subject.name.startsWith("Unknown_"),
  );

  // const totalPhotos = subjects.reduce(
  //   (sum, subject) => sum + (subject.photoCount || 0),
  //   0,
  // );

  return (
    <div className="min-h-screen bg-photo-stone-50 p-6">
      {/* <div className="mb-8">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-3xl font-bold text-photo-stone-800">People</h1>
            <p className="text-photo-stone-600 mt-1">
              Manage and organize people in your photos
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" className="border-photo-stone-300">
              <Download className="w-4 h-4 mr-2" />
              Export All
            </Button>
            <Button className="bg-photo-green-300 hover:bg-photo-green-400 text-white">
              <Plus className="w-4 h-4 mr-2" />
              Add Person
            </Button>
          </div>
        </div>

        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          <Card className="border-photo-stone-200">
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-photo-sage-100 rounded-full flex items-center justify-center">
                  <Users className="w-5 h-5 text-photo-sage-600" />
                </div>
                <div>
                  <p className="text-sm text-photo-stone-600">Total People</p>
                  <p className="text-2xl font-bold text-photo-stone-800">
                    {subjects.length}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="border-photo-stone-200">
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-photo-amber-100 rounded-full flex items-center justify-center">
                  <Camera className="w-5 h-5 text-photo-amber-600" />
                </div>
                <div>
                  <p className="text-sm text-photo-stone-600">Total Photos</p>
                  <p className="text-2xl font-bold text-photo-stone-800">
                    {totalPhotos}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="border-photo-stone-200">
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-photo-emerald-100 rounded-full flex items-center justify-center">
                  <Merge className="w-5 h-5 text-photo-emerald-600" />
                </div>
                <div>
                  <p className="text-sm text-photo-stone-600">
                    Merge Suggestions
                  </p>
                  <p className="text-2xl font-bold text-photo-stone-800">
                    {mergeSuggestions.length}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div> */}

      <></>
      {/* Search */}
      {/* <div className="relative mb-6">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-photo-stone-400 w-4 h-4" />
          <Input
            type="text"
            placeholder="Search people by name..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10 border-photo-stone-300 focus:border-photo-green-300"
          />
        </div> */}
      {/* </div> */}

      <Tabs
        value={selectedTab}
        onValueChange={setSelectedTab}
        className="space-y-4"
      >
        <TabsList className="bg-photo-stone-100">
          <TabsTrigger
            value="all"
            className="data-[state=active]:bg-photo-green-300 data-[state=active]:text-white"
          >
            All People ({filteredSubjects.length})
          </TabsTrigger>
          <TabsTrigger
            value="auto"
            className="data-[state=active]:bg-photo-green-300 data-[state=active]:text-white"
          >
            Auto-Generated ({autoGeneratedSubjects.length})
          </TabsTrigger>
          <TabsTrigger
            value="suggestions"
            className="data-[state=active]:bg-photo-green-300 data-[state=active]:text-white"
          >
            Merge Suggestions ({mergeSuggestions.length})
          </TabsTrigger>
        </TabsList>

        <TabsContent value="all" className="space-y-4">
          <TooltipProvider delayDuration={300}>
            <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
              {filteredSubjects.map(
                ({ id, name, coverUrl, photoCount }, key) => (
                  <SubjectCard
                    key={key}
                    id={id}
                    name={name}
                    coverUrl={coverUrl || ""}
                    photoCount={photoCount || 0}
                  />
                ),
              )}
            </div>
          </TooltipProvider>
        </TabsContent>

        <TabsContent value="auto" className="space-y-4">
          <TooltipProvider delayDuration={300}>
            <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
              {autoGeneratedSubjects.map(
                ({ id, name, coverUrl, photoCount }, key) => (
                  <SubjectCard
                    key={key}
                    id={id}
                    name={name}
                    coverUrl={coverUrl || ""}
                    photoCount={photoCount || 0}
                    isAutoGenerated={true}
                  />
                ),
              )}
            </div>
          </TooltipProvider>
        </TabsContent>

        <TabsContent value="suggestions" className="space-y-4">
          {mergeSuggestions.length === 0 ? (
            <Card className="border-photo-stone-200">
              <CardContent className="p-8 text-center">
                <CheckCircle className="w-12 h-12 text-photo-emerald-300 mx-auto mb-4" />
                <h3 className="text-lg font-semibold text-photo-stone-800 mb-2">
                  No merge suggestions
                </h3>
                <p className="text-photo-stone-600">
                  All people are properly organized!
                </p>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-4">
              {mergeSuggestions.map((suggestion, index) => (
                <Card
                  key={index}
                  className="border-photo-amber-200 bg-photo-amber-50/30"
                >
                  <CardContent className="p-6">
                    <div className="flex items-center justify-between mb-4">
                      <h3 className="text-lg font-semibold text-photo-stone-800">
                        Merge Suggestion
                      </h3>
                      <Badge className="bg-photo-amber-100 text-photo-amber-700">
                        {(suggestion.confidence * 100).toFixed(0)}% match
                      </Badge>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                      <div className="space-y-2">
                        <h4 className="font-medium text-photo-stone-700">
                          {suggestion.person1.name}
                        </h4>
                        <p className="text-sm text-photo-stone-600">
                          {suggestion.person1.photoCount} photos
                        </p>
                        <p className="text-xs text-photo-stone-500">
                          {suggestion.reason}
                        </p>
                      </div>
                      <div className="space-y-2">
                        <h4 className="font-medium text-photo-stone-700">
                          {suggestion.person2.name}
                        </h4>
                        <p className="text-sm text-photo-stone-600">
                          {suggestion.person2.photoCount} photos
                        </p>
                      </div>
                    </div>

                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        onClick={() => setShowMergeDialog(true)}
                        className="bg-photo-green-300 hover:bg-photo-green-400 text-white"
                      >
                        <Merge className="w-3 h-3 mr-1" />
                        Merge
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="border-photo-stone-300"
                      >
                        Dismiss
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default SubjectsGrid;

function SubjectCard({
  id,
  name,
  coverUrl,
  photoCount,
  isAutoGenerated = false,
}: {
  id: string;
  name: string;
  coverUrl: string;
  photoCount: number;
  isAutoGenerated?: boolean;
}) {
  const router = useRouter();

  return (
    <Card className="group relative overflow-hidden border-photo-stone-200 hover:border-photo-green-300 hover:shadow-md transition-all duration-300">
      <CardContent className="p-4">
        <div className="flex flex-col items-center text-center">
          <div className="relative">
            <Image
              src={coverUrl ?? ""}
              alt={name}
              width={96}
              height={96}
              className="h-24 w-24 rounded-full object-cover ring-2 ring-photo-stone-200 group-hover:ring-photo-green-300 transition-all duration-300"
            />
            <div className="pointer-events-none absolute inset-0 hidden items-center justify-center rounded-full bg-black/40 backdrop-blur-sm group-hover:flex">
              <div className="pointer-events-auto flex gap-2">
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      size="icon"
                      variant="secondary"
                      className="rounded-full bg-white/95 hover:bg-white shadow-lg"
                      onClick={() => router.push(`/dashboard/subjects/${id}`)}
                    >
                      <Images className="h-5 w-5" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>View photos</TooltipContent>
                </Tooltip>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      size="icon"
                      variant="secondary"
                      className="rounded-full bg-white/95 hover:bg-white shadow-lg"
                      onClick={async () => await handleDownload(id, "person")}
                    >
                      <Download className="h-5 w-5" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Export / Download all</TooltipContent>
                </Tooltip>
              </div>
            </div>
            {isAutoGenerated && (
              <div className="absolute -top-1 -right-1 w-6 h-6 bg-photo-amber-100 rounded-full flex items-center justify-center">
                <span className="text-xs font-bold text-photo-amber-700">
                  AI
                </span>
              </div>
            )}
          </div>
          <span className="mt-3 text-sm font-medium tracking-tight text-photo-stone-800">
            {name}
          </span>
          <div className="mt-3 flex flex-wrap items-center justify-center gap-2">
            <span className="inline-flex items-center rounded-full gap-1 border border-photo-stone-300 bg-photo-stone-50 px-2 py-1 text-sm font-semibold text-photo-stone-700">
              <Images className="h-3.5 w-3.5" /> {photoCount}
            </span>
            {isAutoGenerated && (
              <span className="inline-flex items-center rounded-full gap-1 border border-photo-amber-300 bg-photo-amber-50 px-2 py-1 text-xs font-semibold text-photo-amber-700">
                Auto-Generated
              </span>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
